name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - master
  pull_request:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setuo node
        uses: actions/setup-node@v1
        with:
          node-version: 14.4.0
      - name: Install dependencies
        run : yarn

      - name: Build React App
        run : yarn build -p

      - name: Setup Firebase CLI
        run : npm install -g firebase-tools

      - name: Deploy Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CIMICINE_FLOW }}'
          channelId: live
          projectId: cimicine-flow
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels